---
- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Restart php-fpm
  ansible.builtin.systemd:
    name: php-fpm
    state: restarted

- name: Restart mariadb
  ansible.builtin.systemd:
    name: mariadb
    state: restarted

- name: Restart snmpd
  ansible.builtin.systemd:
    name: snmpd
    state: restarted

- name: Restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted

- name: Systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restorecon librenms
  ansible.builtin.command: "restorecon -Rv {{ librenms_install_dir }}"
  changed_when: false
...
