---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rocky10-ntp-default
    image: quay.io/rockylinux/rockylinux:10
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    tmpfs:
      - /run
      - /tmp
    exposed_ports:
      - 123/udp
provisioner:
  name: ansible
  inventory:
    host_vars:
      rocky10-ntp-default:
        ntp_upstreams:
          - type: "server"
            host: "time.cloudflare.com"
            nts: true
        ntp_allow:
          - 127.0.0.1
          - 10.0.0.0/8
verifier:
  name: ansible
...
