---
- name: Restorecon lancache
  ansible.builtin.command: restorecon -Rv /srv/lancache
  changed_when: false
  when: ansible_selinux.status == 'enabled'

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Restart lancache
  community.docker.docker_compose_v2:
    project_src: /opt/lancache
    state: restarted

- name: Restart auditd
  ansible.builtin.command: augenrules --load
  changed_when: false
...
