---
- name: Converge
  hosts: all
  become: true
  vars:
    timedatectl_timezone: 'UTC'
    timedatectl_timeservers: ['pool.ntp.org']
    timedatectl_timeservers_fallback: ['time.nist.gov']
  roles:
    - role: base
...
