---
- name: Restart unbound
  ansible.builtin.systemd:
    name: unbound
    state: restarted

- name: Reload unbound
  ansible.builtin.service:
    name: unbound
    state: reloaded

- name: Restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted

- name: Restorecon unbound
  ansible.builtin.command: |
    restorecon -Rv /etc/unbound/
    restorecon -Rv /var/lib/unbound/
    restorecon -v /run/unbound.pid
  changed_when: false
...
