---
lancache_cache_dir: /srv/lancache/data
lancache_logs_dir: /srv/lancache/logs
lancache_cache_disk_size: 500g
lancache_cache_max_age: 3650d
lancache_upstream_dns: 1.1.1.1
lancache_monolithic_image: lancachenet/monolithic:latest
lancache_sniproxy_image: lancachenet/sniproxy:latest
...
