---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rocky10-dns-default
    image: quay.io/rockylinux/rockylinux:10
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    tmpfs:
      - /run
      - /tmp
    exposed_ports:
      - 53/tcp
      - 53/udp
provisioner:
  name: ansible
  inventory:
    host_vars:
      rocky10-dns-default:
        lancache:
          enabled: true
          ipaddrs:
            - 192.168.69.28
        upstreams:
          - 1.1.1.1
          - 9.9.9.9
verifier:
  name: ansible
...
