---
- name: Converge
  hosts: all
  become: true
  vars:
    unbound_num_threads: 2
    unbound_rrset_cache_size: "128m"
    unbound_msg_cache_size: "64m"
    unbound_slabs: 4
    unbound_so_rcvbuf: "4m"
    unbound_so_sndbuf: "4m"
    unbound_so_reuseport: "yes"
  roles:
    - role: dns
...
