---
- name: Prepare instance
  hosts: all
  become: true
  tasks:
    - name: Update metadata and install test deps
      ansible.builtin.command: dnf -y install bind-utils
      args:
        warn: false
...
