---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rocky10-dhcp-default
    image: quay.io/rockylinux/rockylinux:10
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    tmpfs:
      - /run
      - /tmp
    exposed_ports:
      - 67/udp
      - 68/udp
provisioner:
  name: ansible
  inventory:
    host_vars:
      rocky10-dhcp-default:
        interfaces:
          - eth0
        subnets:
          - "192.168.1.0/24"
          - "10.0.1.0/24"
          - "172.16.1.0/24"
        dns_servers:
          - 192.168.129.53
        ntp_servers:
          - 192.168.129.123
verifier:
  name: ansible
...
